### ISSUE TITLE
Format the raw answer data

### ISSUE THREAD

**Issue by oovm** [wjxway/ZhihuLink-Mathematica#3]
- [x] Transform the answer from html to markdown

---

Steps:

- [x] HTML-Formatted
- [x] Parsing the HTML
- [x] Finishing transform to Markdown

**Comment by oovm** [comment]
The raw answer data was something like this:

```php
<p>谢邀</p><p>前面说了阶乘函数是一切特殊函数的基石</p><p>我们要做的就是把关系往阶乘函数上扯</p><p>根据阶乘函数的递推定义</p><p><img src=\"https://www.zhihu.com/equation?tex=%5CGamma+%28z%2B1%29%3Dz%5CGamma+%28z%29\" alt=\"\\Gamma (z+1)=z\\Gamma (z)\" eeimg=\"1\"></p><p>两边求导有</p><p><img src=\"https://www.zhihu.com/equation?tex=+%5CGamma+%27%28z%2B1%29%3Dz%5CGamma+%27%28z%29%2B%5CGamma+%28z%29\" alt=\" \\Gamma '(z+1)=z\\Gamma '(z)+\\Gamma (z)\" eeimg=\"1\"></p><p>两边同除 <img src=\"https://www.zhihu.com/equation?tex=z%5CGamma+%28z%29\" alt=\"z\\Gamma (z)\" eeimg=\"1\"></p><p><img src=\"https://www.zhihu.com/equation?tex=%7B%5Cpsi%28z%2B1%29%3D%5Cfrac+%7B%5CGamma+%27%28z%2B1%29%7D%7B%5CGamma+%28z%2B1%29%7D%7D%3D%7B%5Cfrac+%7B%5CGamma+%27%28z%29%7D%7B%5CGamma+%28z%29%7D%7D%2B%7B%5Cfrac+%7B1%7D%7Bz%7D%7D\" alt=\"{\\psi(z+1)=\\frac {\\Gamma '(z+1)}{\\Gamma (z+1)}}={\\frac {\\Gamma '(z)}{\\Gamma (z)}}+{\\frac {1}{z}}\" eeimg=\"1\"></p><p>圈起来叫 <img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%29\" alt=\"\\psi (z)\" eeimg=\"1\"> , <img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%29\" alt=\"\\psi (z)\" eeimg=\"1\"> 有递推式</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%2B1%29%3D%5Cpsi+%28z%29%2B%7B%5Cfrac+%7B1%7D%7Bz%7D%7D\" alt=\"\\psi (z+1)=\\psi (z)+{\\frac {1}{z}}\" eeimg=\"1\"> 成立</p><p>显然整数时符合</p><p><img src=\"https://www.zhihu.com/equation?tex=%7B%5Cdisplaystyle+H_%7Bn%7D%3D%5Csum+_%7Bk%3D1%7D%5E%7Bn%7D%7B%5Cfrac+%7B1%7D%7Bk%7D%7D%7D\" alt=\"{\\displaystyle H_{n}=\\sum _{k=1}^{n}{\\frac {1}{k}}}\" eeimg=\"1\"></p><hr><p>不过好像还缺了点什么...</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%2B1%29-%5Cpsi+%28z%29%3D%7B%5Cfrac+%7B1%7D%7Bz%7D%7D%5CRightarrow%5Cpsi+%28z%2B1%29%3DH_z%2BC\" alt=\"\\psi (z+1)-\\psi (z)={\\frac {1}{z}}\\Rightarrow\\psi (z+1)=H_z+C\" eeimg=\"1\"></p><ul><li>定解条件不够, 初值条件在哪?</li></ul><p>根据积分定义</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cfrac%7B%7B%5Crm+d%7D%5En%7D%7B%7B%5Crm+d%7Dz%5En%7D%5C%2C%5CGamma%28z%29+%3D+%5Cint_0%5E%5Cinfty+t%5E%7Bz-1%7D+e%5E%7B-t%7D+%28%5Cln+t%29%5E%7Bn%7D+dt+\" alt=\"\\frac{{\\rm d}^n}{{\\rm d}z^n}\\,\\Gamma(z) = \\int_0^\\infty t^{z-1} e^{-t} (\\ln t)^{n} dt \" eeimg=\"1\"></p><p>于是</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi%281%29+%3D+%5Cint_0%5E%5Cinfty+e%5E%7B-t%7D+%5Cln+t%5C+dt+\" alt=\"\\psi(1) = \\int_0^\\infty e^{-t} \\ln t\\ dt \" eeimg=\"1\"></p><p>Emmmmm, 超越指数 积分....</p><hr><p>回到无穷乘积定义式</p><p><img src=\"https://www.zhihu.com/equation?tex=%5CGamma%28z%29+%3D+%5Cfrac%7B%5Cmathrm%7Be%7D%5E%7B-%5Cgamma+z%7D%7D%7Bz%7D+%5Cprod_%7Bn%3D1%7D%5E%7B%5Cinfty%7D+%5Cleft%281+%2B+%5Cfrac%7Bz%7D%7Bn%7D%5Cright%29%5E%7B-1%7D+%5Cmathrm%7Be%7D%5E%7B%5Cfrac%7Bz%7D%7Bn%7D%7D\" alt=\"\\Gamma(z) = \\frac{\\mathrm{e}^{-\\gamma z}}{z} \\prod_{n=1}^{\\infty} \\left(1 + \\frac{z}{n}\\right)^{-1} \\mathrm{e}^{\\frac{z}{n}}\" eeimg=\"1\"></p><p>给它两边取对数, 乘积变求和</p><p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5Clog+%5CGamma+%28z%29+%3D+%5Clog+%28z%29+%2B+%5Cgamma+z+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Clog+%5Cleft%28+%7B1+%2B+%5Cfrac%7Bz%7D%7Bn%7D%7D+%5Cright%29+%E2%80%93+%5Cfrac%7Bz%7D%7Bn%7D%7D+%5Cright%5D%7D+\" alt=\"– \\log \\Gamma (z) = \\log (z) + \\gamma z + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\log \\left( {1 + \\frac{z}{n}} \\right) – \\frac{z}{n}} \\right]} \" eeimg=\"1\"></p><p>再次左右两边求导</p><p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5Cfrac%7B%7B%7B%5CGamma+%5E%5Cprime+%7D%28z%29%7D%7D%7B%7B%5CGamma+%28z%29%7D%7D+%3D+%5Cfrac%7B1%7D%7Bz%7D+%2B+%5Cgamma+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Cfrac%7B%7B1%2Fn%7D%7D%7B%7B1+%2B+z%2Fn%7D%7D+%E2%80%93+%5Cfrac%7B1%7D%7Bn%7D%7D+%5Cright%5D%7D+%5Cquad+z+%5Cmapsto+1\" alt=\"– \\frac{{{\\Gamma ^\\prime }(z)}}{{\\Gamma (z)}} = \\frac{1}{z} + \\gamma + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\frac{{1/n}}{{1 + z/n}} – \\frac{1}{n}} \\right]} \\quad z \\mapsto 1\" eeimg=\"1\"></p><p>令z=1, 有:</p><p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5CGamma%27%281%29+%3D+1+%2B+%5Cgamma+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Cfrac%7B1%7D%7B%7Bn+%2B+1%7D%7D+%E2%80%93+%5Cfrac%7B1%7D%7Bn%7D%7D+%5Cright%5D%7D+\" alt=\"– \\Gamma'(1) = 1 + \\gamma + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\frac{1}{{n + 1}} – \\frac{1}{n}} \\right]} \" eeimg=\"1\"></p><p>把负号移回来</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi%281%29%3D%5Cfrac%7B%5CGamma%27%281%29%7D%7B%5CGamma%281%29%7D%3D+-%5Cleft%281+%2B+%5Cgamma+%E2%80%93+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cfrac%7B1%7D%7B%7Bn%28n+%2B+1%29%7D%7D%7D%5Cright%29%3D+-%5Cgamma\" alt=\"\\psi(1)=\\frac{\\Gamma'(1)}{\\Gamma(1)}= -\\left(1 + \\gamma – \\sum\\limits_{n = 1}^\\infty {\\frac{1}{{n(n + 1)}}}\\right)= -\\gamma\" eeimg=\"1\"></p><p>所以综上所述</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cbbox%5B%23EFF%2C5px%2Cborder%3A2px+solid+red%5D+%7B+H%28z%29%3D%5Cgamma%2B%5Cfrac%7B%5CGamma%27%28z%2B1%29%7D%7B%5CGamma%28z%2B1%29%7D%5Cquad%5Cmathtt%7Bor%7D%5Cquad+H%28z-1%29%3D%5Cpsi%28z%29%2B%5Cgamma+%7D\" alt=\"\\bbox[#EFF,5px,border:2px solid red] { H(z)=\\gamma+\\frac{\\Gamma'(z+1)}{\\Gamma(z+1)}\\quad\\mathtt{or}\\quad H(z-1)=\\psi(z)+\\gamma }\" eeimg=\"1\"></p><figure><noscript><img src=\"https://pic4.zhimg.com/50/v2-84e9380e567822c79bc1b782c150f08e_hd.jpg\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"651\" data-rawheight=\"238\" class=\"origin_image zh-lightbox-thumb\" width=\"651\" data-original=\"https://pic4.zhimg.com/v2-84e9380e567822c79bc1b782c150f08e_r.jpg\"></noscript><img src=\"data:image/svg+xml;utf8,&lt;svg%20xmlns='http://www.w3.org/2000/svg'%20width='651'%20height='238'&gt;&lt;/svg&gt;\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"651\" data-rawheight=\"238\" class=\"origin_image zh-lightbox-thumb lazy\" width=\"651\" data-original=\"https://pic4.zhimg.com/v2-84e9380e567822c79bc1b782c150f08e_r.jpg\" data-actualsrc=\"https://pic4.zhimg.com/50/v2-84e9380e567822c79bc1b782c150f08e_hd.jpg\"></figure><p>当然这个推导过程也表明:</p><p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28x%2B1%29%3D%5Csum+_%7Bk%3D1%7D%5E%7B%5Cinfty+%7D%5Cleft%28%7B%5Cfrac+%7B1%7D%7Bk%7D%7D-%7B%5Cfrac+%7B1%7D%7Bx%2Bk%7D%7D%5Cright%29-%5Cgamma\" alt=\"\\psi (x+1)=\\sum _{k=1}^{\\infty }\\left({\\frac {1}{k}}-{\\frac {1}{x+k}}\\right)-\\gamma\" eeimg=\"1\"></p>
```

Un-readable, needs format.

**Comment by oovm** [comment]
Well, I've done the html-format.

```html
<p>谢邀</p>
<p>前面说了阶乘函数是一切特殊函数的基石</p>
<p>我们要做的就是把关系往阶乘函数上扯</p>
<p>根据阶乘函数的递推定义</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5CGamma+%28z%2B1%29%3Dz%5CGamma+%28z%29\" alt=\"\\Gamma (z+1)=z\\Gamma (z)\" eeimg=\"1\"></p>
<p>两边求导有</p>
<p><img src=\"https://www.zhihu.com/equation?tex=+%5CGamma+%27%28z%2B1%29%3Dz%5CGamma+%27%28z%29%2B%5CGamma+%28z%29\" alt=\" \\Gamma '(z+1)=z\\Gamma '(z)+\\Gamma (z)\" eeimg=\"1\"></p>
<p>两边同除 <img src=\"https://www.zhihu.com/equation?tex=z%5CGamma+%28z%29\" alt=\"z\\Gamma (z)\" eeimg=\"1\"></p>
<p><img src=\"https://www.zhihu.com/equation?tex=%7B%5Cpsi%28z%2B1%29%3D%5Cfrac+%7B%5CGamma+%27%28z%2B1%29%7D%7B%5CGamma+%28z%2B1%29%7D%7D%3D%7B%5Cfrac+%7B%5CGamma+%27%28z%29%7D%7B%5CGamma+%28z%29%7D%7D%2B%7B%5Cfrac+%7B1%7D%7Bz%7D%7D\" alt=\"{\\psi(z+1)=\\frac {\\Gamma '(z+1)}{\\Gamma (z+1)}}={\\frac {\\Gamma '(z)}{\\Gamma (z)}}+{\\frac {1}{z}}\" eeimg=\"1\"></p>
<p>圈起来叫 <img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%29\" alt=\"\\psi (z)\" eeimg=\"1\"> , <img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%29\" alt=\"\\psi (z)\" eeimg=\"1\"> 有递推式</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%2B1%29%3D%5Cpsi+%28z%29%2B%7B%5Cfrac+%7B1%7D%7Bz%7D%7D\" alt=\"\\psi (z+1)=\\psi (z)+{\\frac {1}{z}}\" eeimg=\"1\"> 成立</p>
<p>显然整数时符合</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%7B%5Cdisplaystyle+H_%7Bn%7D%3D%5Csum+_%7Bk%3D1%7D%5E%7Bn%7D%7B%5Cfrac+%7B1%7D%7Bk%7D%7D%7D\" alt=\"{\\displaystyle H_{n}=\\sum _{k=1}^{n}{\\frac {1}{k}}}\" eeimg=\"1\"></p>
<hr>
<p>不过好像还缺了点什么...</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28z%2B1%29-%5Cpsi+%28z%29%3D%7B%5Cfrac+%7B1%7D%7Bz%7D%7D%5CRightarrow%5Cpsi+%28z%2B1%29%3DH_z%2BC\" alt=\"\\psi (z+1)-\\psi (z)={\\frac {1}{z}}\\Rightarrow\\psi (z+1)=H_z+C\" eeimg=\"1\"></p>
<ul>
    <li>定解条件不够, 初值条件在哪?</li>
</ul>
<p>根据积分定义</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cfrac%7B%7B%5Crm+d%7D%5En%7D%7B%7B%5Crm+d%7Dz%5En%7D%5C%2C%5CGamma%28z%29+%3D+%5Cint_0%5E%5Cinfty+t%5E%7Bz-1%7D+e%5E%7B-t%7D+%28%5Cln+t%29%5E%7Bn%7D+dt+\" alt=\"\\frac{{\\rm d}^n}{{\\rm d}z^n}\\,\\Gamma(z) = \\int_0^\\infty t^{z-1} e^{-t} (\\ln t)^{n} dt \" eeimg=\"1\"></p>
<p>于是</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi%281%29+%3D+%5Cint_0%5E%5Cinfty+e%5E%7B-t%7D+%5Cln+t%5C+dt+\" alt=\"\\psi(1) = \\int_0^\\infty e^{-t} \\ln t\\ dt \" eeimg=\"1\"></p>
<p>Emmmmm, 超越指数 积分....</p>
<hr>
<p>回到无穷乘积定义式</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5CGamma%28z%29+%3D+%5Cfrac%7B%5Cmathrm%7Be%7D%5E%7B-%5Cgamma+z%7D%7D%7Bz%7D+%5Cprod_%7Bn%3D1%7D%5E%7B%5Cinfty%7D+%5Cleft%281+%2B+%5Cfrac%7Bz%7D%7Bn%7D%5Cright%29%5E%7B-1%7D+%5Cmathrm%7Be%7D%5E%7B%5Cfrac%7Bz%7D%7Bn%7D%7D\" alt=\"\\Gamma(z) = \\frac{\\mathrm{e}^{-\\gamma z}}{z} \\prod_{n=1}^{\\infty} \\left(1 + \\frac{z}{n}\\right)^{-1} \\mathrm{e}^{\\frac{z}{n}}\" eeimg=\"1\"></p>
<p>给它两边取对数, 乘积变求和</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5Clog+%5CGamma+%28z%29+%3D+%5Clog+%28z%29+%2B+%5Cgamma+z+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Clog+%5Cleft%28+%7B1+%2B+%5Cfrac%7Bz%7D%7Bn%7D%7D+%5Cright%29+%E2%80%93+%5Cfrac%7Bz%7D%7Bn%7D%7D+%5Cright%5D%7D+\" alt=\"– \\log \\Gamma (z) = \\log (z) + \\gamma z + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\log \\left( {1 + \\frac{z}{n}} \\right) – \\frac{z}{n}} \\right]} \" eeimg=\"1\"></p>
<p>再次左右两边求导</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5Cfrac%7B%7B%7B%5CGamma+%5E%5Cprime+%7D%28z%29%7D%7D%7B%7B%5CGamma+%28z%29%7D%7D+%3D+%5Cfrac%7B1%7D%7Bz%7D+%2B+%5Cgamma+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Cfrac%7B%7B1%2Fn%7D%7D%7B%7B1+%2B+z%2Fn%7D%7D+%E2%80%93+%5Cfrac%7B1%7D%7Bn%7D%7D+%5Cright%5D%7D+%5Cquad+z+%5Cmapsto+1\" alt=\"– \\frac{{{\\Gamma ^\\prime }(z)}}{{\\Gamma (z)}} = \\frac{1}{z} + \\gamma + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\frac{{1/n}}{{1 + z/n}} – \\frac{1}{n}} \\right]} \\quad z \\mapsto 1\" eeimg=\"1\"></p>
<p>令z=1, 有:</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%E2%80%93+%5CGamma%27%281%29+%3D+1+%2B+%5Cgamma+%2B+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cleft%5B+%7B%5Cfrac%7B1%7D%7B%7Bn+%2B+1%7D%7D+%E2%80%93+%5Cfrac%7B1%7D%7Bn%7D%7D+%5Cright%5D%7D+\" alt=\"– \\Gamma'(1) = 1 + \\gamma + \\sum\\limits_{n = 1}^\\infty {\\left[ {\\frac{1}{{n + 1}} – \\frac{1}{n}} \\right]} \" eeimg=\"1\"></p>
<p>把负号移回来</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi%281%29%3D%5Cfrac%7B%5CGamma%27%281%29%7D%7B%5CGamma%281%29%7D%3D+-%5Cleft%281+%2B+%5Cgamma+%E2%80%93+%5Csum%5Climits_%7Bn+%3D+1%7D%5E%5Cinfty+%7B%5Cfrac%7B1%7D%7B%7Bn%28n+%2B+1%29%7D%7D%7D%5Cright%29%3D+-%5Cgamma\" alt=\"\\psi(1)=\\frac{\\Gamma'(1)}{\\Gamma(1)}= -\\left(1 + \\gamma – \\sum\\limits_{n = 1}^\\infty {\\frac{1}{{n(n + 1)}}}\\right)= -\\gamma\" eeimg=\"1\"></p>
<p>所以综上所述</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cbbox%5B%23EFF%2C5px%2Cborder%3A2px+solid+red%5D+%7B+H%28z%29%3D%5Cgamma%2B%5Cfrac%7B%5CGamma%27%28z%2B1%29%7D%7B%5CGamma%28z%2B1%29%7D%5Cquad%5Cmathtt%7Bor%7D%5Cquad+H%28z-1%29%3D%5Cpsi%28z%29%2B%5Cgamma+%7D\" alt=\"\\bbox[#EFF,5px,border:2px solid red] { H(z)=\\gamma+\\frac{\\Gamma'(z+1)}{\\Gamma(z+1)}\\quad\\mathtt{or}\\quad H(z-1)=\\psi(z)+\\gamma }\" eeimg=\"1\"></p>
<figure>
    <noscript><img src=\"https://pic4.zhimg.com/50/v2-84e9380e567822c79bc1b782c150f08e_hd.jpg\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"651\" data-rawheight=\"238\" class=\"origin_image zh-lightbox-thumb\" width=\"651\" data-original=\"https://pic4.zhimg.com/v2-84e9380e567822c79bc1b782c150f08e_r.jpg\"></noscript>
    <img src=\"data:image/svg+xml;utf8,&lt;svg%20xmlns='http://www.w3.org/2000/svg'%20width='651'%20height='238'&gt;&lt;/svg&gt;\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"651\" data-rawheight=\"238\" class=\"origin_image zh-lightbox-thumb lazy\" width=\"651\" data-original=\"https://pic4.zhimg.com/v2-84e9380e567822c79bc1b782c150f08e_r.jpg\" data-actualsrc=\"https://pic4.zhimg.com/50/v2-84e9380e567822c79bc1b782c150f08e_hd.jpg\">
</figure>
<p>当然这个推导过程也表明:</p>
<p><img src=\"https://www.zhihu.com/equation?tex=%5Cpsi+%28x%2B1%29%3D%5Csum+_%7Bk%3D1%7D%5E%7B%5Cinfty+%7D%5Cleft%28%7B%5Cfrac+%7B1%7D%7Bk%7D%7D-%7B%5Cfrac+%7B1%7D%7Bx%2Bk%7D%7D%5Cright%29-%5Cgamma\" alt=\"\\psi (x+1)=\\sum _{k=1}^{\\infty }\\left({\\frac {1}{k}}-{\\frac {1}{x+k}}\\right)-\\gamma\" eeimg=\"1\"></p>
```

Now can trying to transform.

**Comment by oovm** [comment]
对于 `<p>*</p>` 而言可以简单地 `ImportString[input,"HTML"]` 来搞定, 但是丢的格式也太多了点

字符串模式手操的话又太烦....

---

尝试使用如下方式解析为XML对象处理

`xml=ImportString[input,{"HTML","XMLObject"}];`

这样的话就可以使用模式匹配解决这个问题了.

**Comment by oovm** [comment]
### 三个主要模式:

```Mathematica
ruleTexline=XMLElement["img",{"src"->__,"alt"->tex__,__},{}]:>StringJoin["$",tex,"$"];
ruleTexdisplay=XMLElement["p",{},{XMLElement["img",{"src"->__,"alt"->tex__,__},{}]}]:>StringJoin["$$",tex,"$$\n"];
rulePara=XMLElement["p",{},{para__}]:>StringJoin[para,"\n"];
```

行内 TeX , 行间 Tex 以及段落模式.

**Comment by oovm** [comment]
### 其他模式

```Mathematica
(*hr 分割线*)
ruleHr=XMLElement["hr",{},{}]:>"\n---\n";
(*mma 解析异常*)
ruleF=XMLElement["figure",{},{}]:>Nothing;
(*noscript 渣画质*)
ruleS=XMLElement["noscript",___]:>Nothing;
(*noscript 源画质*)
ruleImg=XMLElement["img",{___,"data-original"->img__,___},{}]:>StringJoin["[](",img,")"]
(*引用格式*)
ruleLi=XMLElement["li",{},{li__}]:>StringJoin["> ",li,"\n"]
ruleUl=XMLElement["ul",{},{ul__}]:>ul
```

**Comment by oovm** [comment]
```md
谢邀

前面说了阶乘函数是一切特殊函数的基石

我们要做的就是把关系往阶乘函数上扯

根据阶乘函数的递推定义

$$\Gamma (z+1)=z\Gamma (z)$$

两边求导有

$$ \Gamma '(z+1)=z\Gamma '(z)+\Gamma (z)$$

两边同除 $z\Gamma (z)$

$${\psi(z+1)=\frac {\Gamma '(z+1)}{\Gamma (z+1)}}={\frac {\Gamma '(z)}{\Gamma (z)}}+{\frac {1}{z}}$$

圈起来叫 $\psi (z)$ , $\psi (z)$ 有递推式

$\psi (z+1)=\psi (z)+{\frac {1}{z}}$ 成立

显然整数时符合

$${\displaystyle H_{n}=\sum _{k=1}^{n}{\frac {1}{k}}}$$

---

不过好像还缺了点什么...

$$\psi (z+1)-\psi (z)={\frac {1}{z}}\Rightarrow\psi (z+1)=H_z+C$$
> 定解条件不够, 初值条件在哪?

根据积分定义

$$\frac{{\rm d}^n}{{\rm d}z^n}\,\Gamma(z) = \int_0^\infty t^{z-1} e^{-t} (\ln t)^{n} dt $$

于是

$$\psi(1) = \int_0^\infty e^{-t} \ln t\ dt $$

Emmmmm, 超越指数 积分....

---

回到无穷乘积定义式

$$\Gamma(z) = \frac{\mathrm{e}^{-\gamma z}}{z} \prod_{n=1}^{\infty} \left(1 + \frac{z}{n}\right)^{-1} \mathrm{e}^{\frac{z}{n}}$$

给它两边取对数, 乘积变求和

$$\[Dash] \log \Gamma (z) = \log (z) + \gamma z + \sum\limits_{n = 1}^\infty {\left[ {\log \left( {1 + \frac{z}{n}} \right) \[Dash] \frac{z}{n}} \right]} $$

再次左右两边求导

$$\[Dash] \frac{{{\Gamma ^\prime }(z)}}{{\Gamma (z)}} = \frac{1}{z} + \gamma + \sum\limits_{n = 1}^\infty {\left[ {\frac{{1/n}}{{1 + z/n}} \[Dash] \frac{1}{n}} \right]} \quad z \mapsto 1$$

令z=1, 有:

$$\[Dash] \Gamma'(1) = 1 + \gamma + \sum\limits_{n = 1}^\infty {\left[ {\frac{1}{{n + 1}} \[Dash] \frac{1}{n}} \right]} $$

把负号移回来

$$\psi(1)=\frac{\Gamma'(1)}{\Gamma(1)}= -\left(1 + \gamma \[Dash] \sum\limits_{n = 1}^\infty {\frac{1}{{n(n + 1)}}}\right)= -\gamma$$

所以综上所述

$$\bbox[#EFF,5px,border:2px solid red] { H(z)=\gamma+\frac{\Gamma'(z+1)}{\Gamma(z+1)}\quad\mathtt{or}\quad H(z-1)=\psi(z)+\gamma }$$
[](https://pic4.zhimg.com/v2-84e9380e567822c79bc1b782c150f08e_r.jpg)
当然这个推导过程也表明:

$$\psi (x+1)=\sum _{k=1}^{\infty }\left({\frac {1}{k}}-{\frac {1}{x+k}}\right)-\gamma$$
```
